### PR TITLE
Feature/issue 44

### PR DESCRIPTION
**Pull request by dzoccarato**
- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [ ] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [ ] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Related to: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/issues/44

Just a note:
- Built and imported as local nuget source, this is what I can see: 
image
- I've added a folder `images` where I've put the `icon.jpg`  retrieved from https://avatars3.githubusercontent.com/u/32297579?s=460&amp;v=4

Thanks for any feedback!

### CODE REVIEW

**Comment by dzoccarato** [comment]
build issue should fix now: I'd update folder name to uppercase, but this change wasn't reflected on remote repo. I've rearrange the files in order to reflect this change.

**Comment by brandongregoryscott** [comment]
Thanks for this @dzoccarato! @HeyKos while this is just an icon, the file looks pretty blurry (probably compressed from resaving it from GH) - I wonder if we should reach out to design to get a higher res file to use

**Review by brandongregoryscott — APPROVED** [review]

**Comment by brandongregoryscott** [comment]
Hey @dzoccarato - I've received some higher res assets from our design team and uploaded them to our [home repo](https://github.com/AndcultureCode/AndcultureCode/). Can you save this image to the folder instead, and update the fallback URL to the same path? [https://github.com/AndcultureCode/AndcultureCode/blob/main/assets/andculture-glyph%402x.png](https://github.com/AndcultureCode/AndcultureCode/blob/main/assets/andculture-glyph%402x.png)

**Review by brandongregoryscott — APPROVED** [review]
Thanks @dzoccarato!

**Pull request merged**
